### ISSUE TITLE
Click on Hostpot

### ISSUE THREAD

**Issue by vitrinh282** [shaojiankui/PanoramaGL#1]
Why i created new project then after code done, i click on hostpot , they not show anything, but your project is old version is ok , please help me  ( created by xcode 8)

**Comment by shaojiankui** [comment]
which iOS device？ which os version ？

**Comment by vitrinh282** [comment]
mac os 10.12.5 xcode ver 8 , iphone se

**Comment by vitrinh282** [comment]
, btw how to import library without error autorelease

**Comment by shaojiankui** [comment]
use  “-fno-objc-arc” in  build phrase
