### ISSUE TITLE
请问Hostpot热点如何查找？

### ISSUE THREAD

**Issue by AAWayne** [shaojiankui/PanoramaGL#3]
就是我要在6方图中设置多个热点，但是这些热点是怎么找出来？比如我要在一道门上边设置一个热点，但是我不知道这个点是怎么来的
PLHotspot *hotspot = [PLHotspot hotspotWithId:1 texture:hotspotTexture atv:185.0f ath:-30.0f width:0.05 height:0.05];

**Comment by shaojiankui** [comment]
你可以试下 Pano2vr

**Comment by AAWayne** [comment]
谢谢啦，根据你的方法已经能精准的找到我想要的点咯，虽然还是有那么一点小繁琐，但是非常感谢！哈哈
